[development]
dynaconf_merge = true

[development.db]
echo = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:3000", "http://localhost:4200"]

[production]
dynaconf_merge = false

[production.db]
echo = true
uri = "@jinja postgresql://postgres:postgres@db:5432/fastapi_jwt"
connect_args = {}

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["http://localhost:3000", "http://localhost:4200"]
